#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine: install Nginx, listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl,
# it must return a page that contains the string Holberton School
sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo service nginx start
echo "Hello World!" | sudo tee /var/www//html/index.html
