#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt update
sudo apt install -y haproxy
sudo chmod 777 /etc/haproxy/
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy_backup.cfg
echo -e "frontend http_front\n\tbind *:80\n\tmode http\n\tdefault_backend web_backend\n" >> /etc/haproxy/haproxy.cfg
echo -e "backend web_backend\n\tbalance roundrobin\n\tserver 4634-web-01 3.88.184.111:80 check\n\tserver 4634-web-02 34.236.158.184:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart

