#!/usr/bin/env bash                                                                                                        
# connects via SSH spcifying a private key                                                                                  
ssh -i ~/.ssh/school ubuntu@23.22.184.91

